### PR TITLE
Improved the app

### PR DESCRIPTION
**Pull request by developerfromjokela**
* Made UI slight better
* Settings screen is better, when changing the theme, it will change instantly
* When location is not found, it will display no location available.
* Switched to AndroidX
* And more

### CODE REVIEW

**Comment by developerfromjokela** [comment]
Also I fixed the About dialog coloring in dark theme, some text colors were black :wink:

**Comment by norkator** [comment]
Sounds very nice. If you have time, can you explain me more about "AndroidX" I haven't have time to put my mind on this.

**Comment by developerfromjokela** [comment]
> Sounds very nice. If you have time, can you explain me more about "AndroidX" I haven't have time to put my mind on this.

AndroidX is like android.support library, but better, with Android JetPack. You can read more about there: https://developer.android.com/jetpack/androidx

**Comment by developerfromjokela** [comment]
@norkator So, are you merging the PR? :grinning:

**Comment by norkator** [comment]
Don't worry, I will do review and merge if all okay. With me things might take some time if I am not available to do hobby work. I start looking into this now.

**Comment by norkator** [comment]
I updated Play description (English version) and added this github repo there. Was only added at Finnish translation version.

**Comment by norkator** [comment]
Heeeey these changes are impressive!

**Comment by developerfromjokela** [comment]
Awesome! I'm waiting for the update.

**Pull request merged**
