### PR TITLE
4PX strategy and other fixes

### PR DESCRIPTION
**Pull request by developerfromjokela**
- Added 4PX strategy
- Fixed bugs with CainiaoStrategy
- CainiaoStrategy supports a status, when parcel hasn't been collected by post office. Added icon for that status
- Fixed translations where they weren't present
- Small fixes in update notifications

### CODE REVIEW

**Comment by norkator** [comment]
I remember making fire warning app for fire departmen worker once but it was for old android os version. I was there able to receive SMS contents, sadly every each one of them as a privacy issue. I was somehow using broadcast receiver and some flag telling android os that this apps wants to receive sms.

**Comment by developerfromjokela** [comment]
Yes, I was reading somewhere that you can't set a Broadcast Receiver in Manifest because Android doesn't allow that.

**Comment by developerfromjokela** [comment]
What about the rest, 4PX? Is it fine?

**Comment by norkator** [comment]
I need to go sleep now unfortunately so I review it tomorrow. :D obviously it will be great since your code has great all the time.

**Comment by developerfromjokela** [comment]
Ok, good night

**Comment by developerfromjokela** [comment]
So how's the review going? 😁

**Comment by norkator** [comment]
Haha, I am still at my full time job, review starts after 5-6 pm today.

**Comment by developerfromjokela** [comment]
Oh, ok. I'll wait 🙂

**Comment by norkator** [comment]
I tried with code found from aftership 420721289274890249338827578113 not sure does it work right

**Comment by developerfromjokela** [comment]
I can try in an moment

**Comment by norkator** [comment]
Aaa it works but cannot see events... got response:

{"result":1,"message":"操作成功","data":[{"channelTrackCode":null,"ctEndCode":"US","ctEndName":"America","ctStartCode":"CN","ctStartName":"China","duration":22.0,"queryCode":"420721289274890249338827578113","serverCode":"420721289274890249338827578113","shipperCode":"302744164149","status":1,"tracks":[{"tkCategoryCode":null,"tkCategoryName":null,"tkCode":null,"tkDate":1596587400000,"tkDesc":"Missent","tkLocation":"Bull Shoals,AR","tkTimezone":null},{"tkCategoryCode":null,"tkCategoryName":null,"tkCode":null,"tkDate":1596581640000,"tkDesc":"Arrival at unit","tkLocation":"Bull Shoals,AR","tkTimezone":null},{"tkCategoryCode":null,"tkCategoryName":null,"tkCode":null,"tkDate":1596054346000,"tkDesc":"Tendered for delivery","tkLocation":"Memphis,TN","tkTimezone":null},{"tkCategoryCode":null,"tkCategoryName":null,"tkCode":null,"tkDate":1596047727000,"tkDesc":"Dn received","tkLocation":"Memphis,TN","tkTimezone":null},{"tkCategoryCode":null,"tkCategoryName":null,"tkCode":null,"tkDate":1595909574000,"tkDesc":"Dn send","tkLocation":"Melrose Park,IL","tkTimezone":null},{"tkCategoryCode":null,"tkCategoryName":null,"tkCode":null,"tkDate":1595865650000,"tkDesc":"Encoded","tkLocation":"Melrose Park,IL","tkTimezone":null},{"tkCategoryCode":null,"tkCategoryName":null,"tkCode":null,"tkDate":1595865634000,"tkDesc":"Received","tkLocation":"Melrose Park,IL","tkTimezone":null},{"tkCategoryCode":"D","tkCategoryName":"","tkCode":"FPX_D_STPP","tkDate":1595692800000,"tkDesc":"In transit, it's progressing through post network","tkLocation":"ORD","tkTimezone":""},{"tkCategoryCode":"M","tkCategoryName":"","tkCode":"FPX_M_ATA","tkDate":1595587860000,"tkDesc":"Arrived at the destination airport","tkLocation":"ORD","tkTimezone":"UTC-06:00"},{"tkCategoryCode":"I","tkCategoryName":"","tkCode":"FPX_I_RCUK","tkDate":1595486280000,"tkDesc":"Released from customs: customs cleared.","tkLocation":"ORD","tkTimezone":"UTC+02:00"},{"tkCategoryCode":"M","tkCategoryName":"","tkCode":"FPX_M_DFOA","tkDate":1595445720000,"tkDesc":"Shipment departed from airport of origin country","tkLocation":"CAN","tkTimezone":"UTC+08:00"},{"tkCategoryCode":"M","tkCategoryName":"","tkCode":"FPX_M_AAHK","tkDate":1595245440000,"tkDesc":"Arrived at hong kong hub.","tkLocation":"ORD","tkTimezone":""},{"tkCategoryCode":"C","tkCategoryName":"","tkCode":"FPX_C_ADFF","tkDate":1595066029000,"tkDesc":"Depart from facility to service provider.","tkLocation":"Shenzhen,China","tkTimezone":"UTC+08:00"},{"tkCategoryCode":"C","tkCategoryName":"","tkCode":"FPX_C_SPLS","tkDate":1594797034000,"tkDesc":"4px picked up shipment.","tkLocation":"Shenzhen,China","tkTimezone":"UTC+08:00"},{"tkCategoryCode":"C","tkCategoryName":"","tkCode":"FPX_C_AAF","tkDate":1594797034000,"tkDesc":"Shipment arrived at facility and measured.","tkLocation":"Shenzhen,China","tkTimezone":"UTC+08:00"}]}],"tag":"14"}

**Comment by norkator** [comment]
image

**Comment by developerfromjokela** [comment]
Let me check where does that null pointer occur

**Comment by norkator** [comment]
Yes no problem! I go do other things, will get back soon again. I release update when all is fine.

**Comment by developerfromjokela** [comment]
Ok. Found out that those didn't have tkCodes. I've managed to extract what parcel's statuses mean, and now did "delivered" detection properly.

Meanwhile I also did the issue #24, commit coming shortly

**Comment by developerfromjokela** [comment]
And did this empty view in archive and main menu, because in my opinion, it's great user experience when you see the app telling that list is empty:
Screenshot_1596732546
Screenshot_1596732623

**Comment by norkator** [comment]
🥇 Two people here looking this "small" but really big user experience making change. I tested it out, very very nice addition. Also 4PX events are loading! 🥇 👍  super work!

**Comment by norkator** [comment]
image
nice!

**Comment by norkator** [comment]
Release is out.

**Comment by developerfromjokela** [comment]
Excited waiting the update become live in Google Play 😆

**Comment by norkator** [comment]
Mee too!

**Comment by developerfromjokela** [comment]
But why does the play store say that this app contains ads? Does it? I haven't seen so far any of them

**Comment by developerfromjokela** [comment]
Kuvakaappaus 2020-08-06 23-06-31

**Comment by norkator** [comment]
There was ads long time ago till decided to remove them because too annoying for app like this. I updated developer console details and set it not to have ads.

**Comment by developerfromjokela** [comment]
Ok.

**Comment by ristomatti** [comment]
Great work! The new "empty" screens make a lot more polished look and improve user experience. :+1:

**Comment by ristomatti** [comment]
> But why does the play store say that this app contains ads? Does it? I haven't seen so far any of them

There used to be this "view an ad" button on the about view (or menu). I'm too lazy to check if it's still there but if it is, I'd assume that'd cause Play Store to display the message. Or maybe it's in the XML manifest or similar? Although I'm a long time Java developer I don't have direct Android experience, only through React Native...

**Comment by norkator** [comment]
> > But why does the play store say that this app contains ads? Does it? I haven't seen so far any of them
> 
> There used to be this "view an ad" button on the about view (or menu). I'm too lazy to check if it's still there but if it is, I'd assume that'd cause Play Store to display the message. Or maybe it's in the XML manifest or similar? Although I'm a long time Java developer I don't have direct Android experience, only through React Native...

Those are deleted and soon play store should not so that because I had toggle on contains ads at play store.

**Comment by ristomatti** [comment]
That might even boost interest. Especially as Posti's own app has started displaying inline adds between tracked packages which I find quite annoying. Especially as a new ad sometimes appears when refreshing the statuses if the previous one has been cleared...

**Comment by norkator** [comment]
> That might even boost interest. Especially as Posti's own app has started displaying inline adds between tracked packages which I find quite annoying. Especially as a new ad sometimes appears when refreshing the statuses if the previous one has been cleared...

That is good news that they first create great app and now kill it slowly with ads

**Comment by ristomatti** [comment]
Yep but it still has some advantages that I doubt can be implemented by a third party unfortunately. For example on home delivery packages they'll inform you through the app day or two before and allow selecting if you want the package delivered home or to a Posti pickup point of your choosing.

Another less important but also useful feature is that you'll see some of the tracked packages appearing automatically. Occasionally when buying something from let's say AliExpress, the tracking code might change midway without the seller knowing about it. I doubt they offer an API for this either? 

These reasons are why I have the app installed although I primarily use PS for tracking (not to mention logging/archiving and support for other couriers).

**Comment by developerfromjokela** [comment]
"For example on home delivery packages they'll inform you through the app day or two before and allow selecting if you want the package delivered home or to a Posti pickup point of your choosing."

Is this possible to do in their website or outside their app? And does that require some kind of authorization?

**Comment by ristomatti** [comment]
> Is this possible to do in their website or outside their app? And does that require some kind of authorization?

I believe there might be just a simple SMS if I wasn't registered on their app actually. Definitely there has to be another way to pick the location. 

For my second point the alternative to new packages appearing automatically (strangely happens only with some deliveries) would be to wait for the paper note to arrive when the package can be picked. As we all probably know it will often delay things for one day.

**Pull request merged**
