### PR TITLE
Added the Push Receiver

### PR DESCRIPTION
**Pull request by developerfromjokela**
(@norkator You have to set the firebase json config from the firebase control panel, and start the server script)

Issue #1

### CODE REVIEW

**Comment by developerfromjokela** [comment]
Ok, Have you tested it yet?

**Comment by norkator** [comment]
I have problems and one note about this:

image

All seems to be fine, I have clean and rebuild project on Android Studio but still it's whining about this, any idea why?

Can I bring ParcelService.java and PushService.java main carrier update logic to own class or something that there would not be repeating code?

**Comment by developerfromjokela** [comment]
If you success at it, of course! If you've found to make one single Thread for the updater, I agree. : smile:

**Comment by developerfromjokela** [comment]
One thing about that error, have you checked if the firebase dependency is defined in the `build.gradle` file?

**Comment by developerfromjokela** [comment]
Mine is working, I find no problems when building the app.
Can you try to get it working on my repo?

**Comment by developerfromjokela** [comment]
While you're trying to solve that, I'm making one class for the update logic.

**Comment by norkator** [comment]
Now it's not whining anymore, only crashing with: "Default FirebaseApp is not initialized in this process com.nitramite.paketinseuranta. Make sure to call FirebaseApp.initializeApp(Context) first."

I have been busy with other repo and now need to do other things.  I get back to this later.

**Comment by developerfromjokela** [comment]
Ok. I'll try to fix it. :smile:

**Comment by norkator** [comment]
Thanks!

**Comment by developerfromjokela** [comment]
Now it should work

**Comment by norkator** [comment]
image

Now updating manually by swipe will run indefinitely, looks like broadcast receiver no longer works? I am not sure.

**Comment by developerfromjokela** [comment]
Ok. Thanks for informing. I'll take a look.

**Comment by developerfromjokela** [comment]
I forgot to put the `stopSelf()` back after changes. That was causing the issue.

**Comment by developerfromjokela** [comment]
Now it should work

**Comment by norkator** [comment]
I have it running now. Earlier problem is fixed, excellent!

image

Is this setting taken into count that it will only trigger update if last update has passed this set time? (I don't see it being taken into count) should it be?

I was about to ask about how this works "/topics/update_parcels" but I see it on cron job, nice! I let this run now and  see how it works :)

So far excellent work!

**Comment by norkator** [comment]
Do I need to do tests on physical device?

**Comment by developerfromjokela** [comment]
Unfortunately I don't have any trackable parcels, but if you can test it on your device a few days if it ever pushes an notification.

**Comment by developerfromjokela** [comment]
About that update Interval, I haven't yet figured out how to set the Interval, as it depends on the Cron job. Maybe we can save the last update date to preferences and see how much time has passed since the last check and follow the user's interval. (The push notification will eventually reach the device but if the interval is not over yet it will not attempt to update anything).

I'll try implementing that later today.

**Comment by norkator** [comment]
That is great!

**Comment by developerfromjokela** [comment]
Now I've implemented the interval. I forgot to declare the service in Manifest before, and the Push notifications weren't working. Can you test and confirm that notifications do work now?

**Comment by developerfromjokela** [comment]
By setting the interval to 0, it will update every five minutes. The interval can be a decimal number i.e. 0.2 (20 minutes).

**Comment by norkator** [comment]
"Can you test and confirm that notifications do work now?"
=> Yes, doing testing now.

**Comment by norkator** [comment]
Hah... I didn't have curl installed at all for my Linux server or phpcurl package. Now running cron job actually does something but not receiving with virtual device so will change to physical with Google account.

**Comment by developerfromjokela** [comment]
Ok, weird. Does your virtual device have Google Play services installed? Lack of it may be the cause

**Comment by developerfromjokela** [comment]
You can try enabling debugging and manually running the server script to ensure that it's working

**Comment by norkator** [comment]
I changed topic name due "W/FirebaseMessaging: Format /topics/topic-name is deprecated. Only 'topic-name' should be used in subscribeToTopic."

**Comment by norkator** [comment]
I am running manually cron job which seems to be working normally?

Sending the push message
Push message sent.
Exiting the script

**Comment by norkator** [comment]
Also I followed this https://stackoverflow.com/questions/37351354/firebase-cloud-messaging-notification-not-received-by-device and run manually push update when app's were in foreground, still nothing, has been trying many times with two devices. Play services is fine with all permissions enabled.

**Comment by developerfromjokela** [comment]
I've updated the server code to show errors if any occurs. Try again after updating

**Comment by developerfromjokela** [comment]
Is it working?

**Comment by norkator** [comment]
ERROR:
Field "data" must be a JSON array: []

**Comment by developerfromjokela** [comment]
I've fixed it and tried running myself, and it works. Try again after pulling the repo's new version.

**Comment by developerfromjokela** [comment]
I've added JSON Response parser to the script for debugging purposes, doublecheck if you have `php-json` extension installed.

**Comment by norkator** [comment]
Yes it's fine. I also has php api's running on this same server which are processing json made by same extension.

**Comment by norkator** [comment]
Well this error is coming from google fcm api so must be problem with data.

**Comment by norkator** [comment]
https://stackoverflow.com/questions/45396133/fcm-field-data-must-be-a-json-array

"By adding JSON_FORCE_OBJECT to json_encode() it will add missing braces so it should be something like this:

json_encode($fields ,JSON_FORCE_OBJECT));"

**Comment by norkator** [comment]
I now get message_id back with this modification but returned http code from curl is 0 so it will always say "ERROR:"...

**Comment by norkator** [comment]
I'm using PHP 7.3.14 if that affects anywhere?

**Comment by norkator** [comment]
LOL I needed to change naming back to /topic/ one because google fcm api started throwing "error":"InvalidRegistration"

**Comment by norkator** [comment]
I set update timing to zero and it works too, I see update toast on phone and parcel status updating. Excellent!

**Comment by norkator** [comment]
I just decided to merge it because I see no problem. If you want to make more changes, do new pull request or can you make direct braches?

**Comment by developerfromjokela** [comment]
> I now get message_id back with this modification but returned http code from curl is 0 so it will always say "ERROR:"...

It should not do that. Have you updated it to the latest version? There was a bug at some point that said ERROR every time

**Comment by developerfromjokela** [comment]
But great that it works.

**Comment by developerfromjokela** [comment]
> JSON_FORCE_OBJECT

Which part of code are you referring to?

**Comment by norkator** [comment]
Part where data is json_encoded before curl

**Comment by norkator** [comment]
I have most likely missed updates with server part. I check it.

**Comment by developerfromjokela** [comment]
Ok.

**Pull request merged**
