### PR TITLE
Fixed some spelling errors

### PR DESCRIPTION
**Pull request by masaseta**
I found some little spelling errors in Finnish language on the app. I fixed these and this is also my first little contribution to this project.

### CODE REVIEW

**Comment by developerfromjokela** [comment]
👍

**Review by norkator — APPROVED** [review]
Totally approving this. Great improvement to have correctly written language.

**Review by ristomatti — APPROVED** [review]
Definite approval as a spelling nerd from me also. I've been planning on doing a similar PR but never got myself to actually do it. I believe you've been a little too cautious with these changes though. There's nothing wrong with suggesting complete rewordings but these are welcome improvements altogether IMO. 🙂

**Comment by masaseta** [comment]
Yea, I thought that too! Maybe I sometime do the complete rewording to like "more-professional" words. Now I mostly corrected spelling errors.

**Pull request merged**
