### PR TITLE
Paid unpaid option feature

### PR DESCRIPTION
**Pull request by norkator**
Screenshot 2021-01-15 at 14 45 43

Screenshot 2021-01-15 at 14 45 51

### CODE REVIEW

**Comment by norkator** [comment]
Open as draft because front page view has problem loading status, need to fix that first

**Comment by ristomatti** [comment]
Is it the paid or unpaid icon on the list view screenshot? If unpaid would it make sense to have a red circle and like crossing over the dollar sign if it's unpaid? Like a traffic sign for no parking or something similar? 😄

**Comment by norkator** [comment]
> Is it the paid or unpaid icon on the list view screenshot? If unpaid would it make sense to have a red circle and like crossing over the dollar sign if it's unpaid? Like a traffic sign for no parking or something similar? 😄

Dollar sign yes. For one user should it be different? Can you do change for your liking?

**Comment by norkator** [comment]
> Is it the paid or unpaid icon on the list view screenshot? If unpaid would it make sense to have a red circle and like crossing over the dollar sign if it's unpaid? Like a traffic sign for no parking or something similar? 😄

I mean theres no icon at all normally so people dont notice change

**Comment by norkator** [comment]
Making release today, otherwise this would sit here next week. Changes are welcome tho as a new branch.

**Pull request merged**
