### PR TITLE
Developing tests for strategies (junit)

### PR DESCRIPTION
**Pull request by norkator**
**Idea / Goal**
1. Pull working tracking number from AfterShip with css query using already existing Jsoup.
2. Write tests into one strategy test class.
3. Run tests with Jenkins with each commit.

This way we stay on top when courier changes api etc.

**I only add few for testing to see how long afterShip gives responses before blocking IP or something like that**

### CODE REVIEW

**Comment by norkator** [comment]
image

Looks good to me

**Comment by ristomatti** [comment]
Brilliant idea! I don't know how you've set the hooks to run this but every commit sounds a bit extreme. Maybe for each pull request?

Ideally these would run periodically but I have no idea if it's possible without an external trigger/hook. (I'm assuming you're using GitHub's features to do this)

**Comment by norkator** [comment]
> Brilliant idea! I don't know how you've set the hooks to run this but every commit sounds a bit extreme. Maybe for each pull request?
> 
> Ideally these would run periodically but I have no idea if it's possible without an external trigger/hook. (I'm assuming you're using GitHub's features to do this)

I just run these with periotically checking for changes, no hooks (requires to open ports) unless I didnt get what you mean. I can try do something like only run these at master branch so if any fails can do fix branch

**Review by ristomatti — COMMENTED** [review]
LGTM

**Comment by norkator** [comment]
> LGTM

Today I implement tests for rest of them

**Pull request merged**
