### PR TITLE
Change whole application from Java to Kotlin

### PR DESCRIPTION
**Pull request by norkator**
**This is draft!** opening draft PR just so this is more visible for people.

* I will use in some point Android Studio integrated converter but for now will for learning purposes do by hand few/many files over time.
* I will only do necessary conversion, not improve code overall quality.
* Anyone else who is interested can join to this conversion too.

@ristomatti @developerfromjokela if you have any comments on this, let me know.

### CODE REVIEW

**Comment by ristomatti** [comment]
I would argue it might not make sense to convert everything at one go anyway. As the file name changes, all git history to why anything was done is more or less lost. It might be possible to preserve some of it with some git trickery though. Something like:
1. Run conversion to a java file, copy the result somewhere
2. Revert the change and rename the .java file extension to .kt
3. Commit the rename
4. Replace the contents with the conversion output

These steps could be done to multiple files at once.

Of course its tedious and this is your repo, so do as you please but just making a note on the lost history (which can often be valuable after a long time between edits to a file)..

**Comment by norkator** [comment]
Very good input! I didn't think of history at all.

**Comment by ristomatti** [comment]
After doing hours of detective work to try to figure out why some cryptic code exists enough times you start to appreciate this kind of stuff. Git is pretty smart in ignoring even file renames/moves on the line level history but not when the lines are changed at the same time the file name/path change.

If doing big refactoring, I've made a habit to check what the "show annotations" (git blame) look like after a commit and if I see the history gone, I'll try to redo the change more incrementally. Usually doing the renames/moves in a separate commit first does the trick. This does not seem to work 100% of times and sometimes the lost history just has to be accepted.

Of course the history is not completely lost as you can check the commit when the file was created, see what files were removed and try to figure out the old file name. It's just very painful to diff changes several "layers" back if you want to find out why some specific line(s) were added.

**Comment by norkator** [comment]
Probably better not to do this transformation after all for this project :octocat:

**Comment by norkator** [comment]
I leave this branch to exist.

**Pull request closed without merging**
